export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-stone-50">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600&display=swap');
        body { font-family: 'DM Sans', sans-serif; }
        .font-serif { font-family: 'DM Serif Display', serif !important; }
      `}</style>

      {/* Nav */}
      <nav className="border-b border-stone-100 bg-white/90 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center">
          <a href="/" className="font-serif text-xl text-stone-900 hover:text-amber-700 transition-colors">
            Gift AI
          </a>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-serif text-4xl text-stone-900 mb-3 tracking-tight">Terms of Service</h1>
        <p className="text-stone-400 text-sm mb-12">Last updated: April 7, 2026</p>

        <div className="space-y-10 text-stone-600 text-sm leading-relaxed">

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Gift AI (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service. These Terms apply to all visitors, users, and others who access the Service.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">2. Description of Service</h2>
            <p>
              Gift AI is a free gift recommendation tool that uses artificial intelligence to suggest products based on information you provide about a gift recipient. The Service is provided for personal, non-commercial use. We earn affiliate commissions when users purchase products through links on the Service.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">3. Use of the Service</h2>
            <p className="mb-3">You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Use the Service in any way that violates applicable laws or regulations</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its related systems</li>
              <li>Use automated tools to scrape, crawl, or extract data from the Service</li>
              <li>Reverse engineer, decompile, or otherwise attempt to extract the source code of the Service</li>
              <li>Use the Service to transmit spam, malware, or any harmful content</li>
              <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">4. Accounts</h2>
            <p>
              Creating an account is optional. If you create an account, you are responsible for maintaining the security of your credentials and for all activity that occurs under your account. You must provide accurate information when creating an account. We reserve the right to terminate accounts that violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">5. Affiliate Disclosure</h2>
            <p>
              Gift AI participates in affiliate programs including the Amazon Associates Program. We earn a commission when you click a product link and make a purchase. This commission comes at no additional cost to you — the price you pay is the same as if you visited the retailer directly. Our recommendations are based on relevance and quality, not commission rates.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">6. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS. WE MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THE ACCURACY, COMPLETENESS, OR SUITABILITY OF ANY GIFT RECOMMENDATIONS PROVIDED THROUGH THE SERVICE.
            </p>
            <p className="mt-3">
              Gift recommendations are generated by artificial intelligence and are provided for informational purposes only. We do not guarantee that any recommended product will be suitable, available, or satisfactory to any recipient.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">7. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, GIFT AI AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF PROFITS, OR ANY DISSATISFACTION WITH PURCHASED PRODUCTS.
            </p>
            <p className="mt-3">
              We are not responsible for the quality, safety, legality, or availability of products purchased through third-party retailers. Any disputes regarding products should be directed to the retailer from whom the product was purchased.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">8. Third-Party Links</h2>
            <p>
              The Service contains links to third-party websites and services, including retailers such as Amazon. These links are provided for your convenience. We have no control over the content, privacy policies, or practices of third-party sites and accept no responsibility for them. We encourage you to review the privacy policy of any third-party site you visit.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">9. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are owned by Gift AI and are protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works based on the Service without our express written permission.
            </p>
            <p className="mt-3">
              Product names, images, and descriptions displayed through the Service are the property of their respective owners and are used for informational purposes under applicable fair use principles.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">10. User Content</h2>
            <p>
              By providing information through the Service (such as quiz answers or saved partner profiles), you grant us a non-exclusive, royalty-free license to use that information to provide and improve the Service. You represent that you have the right to provide this information and that it does not violate any third party's rights.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">11. Privacy</h2>
            <p>
              Your use of the Service is also governed by our{" "}
              <a href="/privacy" className="text-amber-700 hover:underline">Privacy Policy</a>,
              which is incorporated into these Terms by reference.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">12. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may do so by contacting us at the email address below.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">13. Changes to Terms</h2>
            <p>
              We may revise these Terms at any time by updating this page. Changes are effective when posted. Your continued use of the Service after changes are posted constitutes your acceptance of the revised Terms. We encourage you to review these Terms periodically.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">14. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in the United States.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-stone-900 text-base mb-3">15. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-3 font-medium text-stone-800">
              Gift AI<br />
              <a href="mailto:support@giftai.app" className="text-amber-700 hover:underline">support@giftai.app</a>
            </p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-stone-200">
          <a href="/" className="text-sm text-amber-700 hover:underline">← Back to Gift AI</a>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-stone-900 text-stone-500 mt-12">
        <div className="max-w-5xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
          <p>© {new Date().getFullYear()} Gift AI. All rights reserved.</p>
          <div className="flex gap-4">
            <a href="/privacy" className="hover:text-white transition-colors">Privacy Policy</a>
            <a href="/terms" className="hover:text-white transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}